### ISSUE TITLE
Simple DOCX with simple JSON not rendering

### ISSUE THREAD

**Issue by HomeBro** [jreyesr/n8n-nodes-carbonejs#6]
Hi,

I can't figure out, what I'm doing wrong.

I've installed your **excellent!** node (v1.1.1) in N8n (v1.34.0) and tested "Render" with a very simple DOCX and a very simple JSON for a start to get to know you Carbone Node. N8N Flow attached.

[My_workflow_8.json](https://github.com/jreyesr/n8n-nodes-carbonejs/files/14771076/My_workflow_8.json)
[Hello.docx](https://github.com/jreyesr/n8n-nodes-carbonejs/files/14771080/Hello.docx)

![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/35006446/1b23273e-cf0d-4a5a-a4ac-58f8b10642a0)
![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/35006446/58858203-61d3-4cb4-b17d-175e9aacce35)
![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/35006446/df2b3d17-df93-427a-b324-944a576b88d0)

When I run the Flow the result is a DOCX without the tags but also no rendering of the JSON data.

![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/35006446/9a3b2b12-60d1-4e88-a4fb-0f62e4d74749)

I noticed that after the Merge node the {{ tag }} has been removed from the DOCX. Is this perhaps the problem?
![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/35006446/00309b35-e56b-49d4-8339-b246e9d13799)

I can see the JSON data after the Merge.
![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/35006446/937354ff-e24a-4b28-b3ee-3db9d91e4ff7)

I haven't put anything in the "Context" in the Carbone node.
![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/35006446/5889bcae-58ec-47ec-a6d1-149892f4e2a8)

Did I miss something?

Regards,
Kim

**Comment by jreyesr** [comment]
Hello, and thanks a lot for using the node and for the kind words!

I believe that the problem is that there is nothing on the node's Context field. That is what is used to fill the template (i.e. the Context field is what appears on `{ d.XYZ }` on the Carbone template). Since your workflow has an empty Context, the tag is replaced by whitespace.

The fix is to pass `{{ JSON.stringify($json) }}` directly to the Context node, so the template is aware of your JSON data:

![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/23390438/448cbe51-b45a-4351-93dc-24e3b3b99168)

Try that and let me know if it fixes the issue, it did for me:

![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/23390438/c8cb59c7-7d10-4dc4-ae2c-8d731770a022)

---

Also, a few other points:

> I noticed that after the Merge node the {{ tag }} has been removed from the DOCX. Is this perhaps the problem?

Yeah, that is slightly weird. The reason for the tag disappearing after the merge node is that those Binary files are _the same ones_ that the Carbone node uses. In other words, once the Carbone node alters the `data` Binary property, it is automatically altered on previous nodes too:

![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/23390438/2d4468e7-00aa-4f2c-bfc5-50ac42f514de)

Thus, what you're seeing on _the Merge node_ is actually the output of the Carbone node, which couldn't find the tags because of the empty Context. You can verify that when you use a different Binary name for the Property Name Out, which is where the rendered document is placed:

![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/23390438/d0143b1f-6c26-458f-865b-8bb47082f084)

Once you do that, a new Binary file magically appears on previous steps too. I believe N8N does this for efficiency, so files (which can be very large) aren't copied needlessly: only a _reference_ to them is passed between steps.

---

The behavior of the template's context `{ d }` being taken from an explicit field instead of implicitly from the node's JSON input is admittledly slightly confusing, but I followed what the HTTP Request node does: when you enable the Send Body switch, you also have to provide a JSON body explicitly, instead of the node just taking it from the JSON input:

![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/23390438/1eaa7bf3-4d5f-4add-9255-2056210c401e)

This is different from Node-RED, where the input to a node is implicitly the payload, forcing you to add a transformation node previously to massage the input to the required shape.

**Comment by HomeBro** [comment]
Thank you so much - It's working now and it all makes sense to me :)
